version: 2.1
jobs:
    asam:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: |
              lscpu
              echo Hello,subscribe it

workflows:
    version: 2.1
    build:
        jobs:
        - asam